# Generated by Django 4.1.3 on 2022-12-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologerapplogic', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('socialId', models.AutoField(primary_key=True, serialize=False)),
                ('socialname', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
