# Generated by Django 4.1.3 on 2022-12-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrologerapplogic', '0003_sociallinks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallinks',
            old_name='socialname',
            new_name='socialmedianame',
        ),
    ]
