# Generated by Django 4.1.3 on 2022-12-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologerapplogic', '0005_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogimg',
            field=models.FileField(upload_to='blogimg/'),
        ),
    ]
