# Generated by Django 4.1.3 on 2022-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologerapplogic', '0006_alter_blog_blogimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogimg',
            field=models.FileField(upload_to='static/'),
        ),
    ]
